#!/bin/bash
source .env
curl -XPOST -H "Content-Type: application/json" http://elastic:$ELASTICSEARCH_PASSWORD@localhost/es/_security/user/$ELASTICSEARCH_USERNAME/_password -d "{ \"password\": \"$ELASTICSEARCH_PASSWORD\" }"
