version: "2.1"
services:
  code-server:
    image: lscr.io/linuxserver/code-server:latest
    networks:
      - homelab
    container_name: codeserver
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - PASSWORD=${PASSWORD}
      - HASHED_PASSWORD=${HASHED_PASSWORD}
      - SUDO_PASSWORD=${SUDO_PASSWORD}
      - SUDO_PASSWORD_HASH=${SUDO_PASSWORD_HASH}
      - PROXY_DOMAIN=${PROXY_DOMAIN}
      - DEFAULT_WORKSPACE=${DEFAULT_WORKSPACE}
    ports:
      - ${PORT}:8443
    restart: unless-stopped
    volumes:
      - ${CONFIG_PATH}:/config

networks:
  homelab:
    external: true
